apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mosquitto-exporter
  name: mosquitto-exporter
spec:
  ports:
  - name: "9234"
    port: 9234
    targetPort: 9234
  type: LoadBalancer
  selector:
    io.kompose.service: mosquitto-exporter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mosquitto-exporter
  name: mosquitto-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: mosquitto-exporter
    spec:
      containers:
      - image: sapcc/mosquitto-exporter:0.5.0
        env:
          - name: BROKER_ENDPOINT
            value: "tcp://mosquitto:1883"
          - name: MQTT_USER
            value: "admin"
          - name: MQTT_PASS
            value: "public"
        name: mosquitto-exporter
        ports:
        - containerPort: 9234
        resources: {}
      restartPolicy: Always


