# Default values for mosquitto
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# images
rulesEngineImage: juanman/docker-support-rulesengine:latest

edgex_rules_engine:
  name: "edgex-support-rulesengine"
  port: 48075

# volumes
volumes:
  accessMode: ReadWriteOnce
  size: 250Mi
  logs:
    size: 500Mi
    claimName: "logs-claim"
    path: "/tmp/edgex/logs"
    name: "logs"
    diskName: "logs-disk"
    mountPath: "/edgex/logs"

#volumes:
#  data_db:
#    name: "db-data"
#    path: "/data/db"
#  logs:
#    name: "edgex-logs"
#    path: "/edgex/logs"
#  consul_config:
#    name: "consul-config"
#    path: "/consul/config"
#  consul_data:
#    name: "consul-data"
#    path: "/consul/data"

