apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-influxdb-data-disk
  labels:
    name: edgex-influxdb-data-disk
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/influxdb-1
  persistentVolumeReclaimPolicy: Delete
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: edgex-influxdb-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: edgex-influxdb
  labels:
    name: edgex-influxdb
spec:
  ports:
    - port: 8086
      name: "http"
    - port: 8088
      name: "udp"
  selector:
    name: edgex-influxdb
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: edgex-influxdb
  labels:
    name: edgex-influxdb
spec:
  containers:
    - name: edgex-influxdb
      image: influxdb:alpine
      env:
        - name: INFLUXDB_DB
          value: "edgex"
        - name: INFLUXDB_ADMIN_USER
          value: "edgex"
        - name: INFLUXDB_ADMIN_PASSWORD
          value: "edgex"
#        - name: INFLUXDB_HTTP_ENABLED
#          value: "true"
#        - name: INFLUXDB_BIND_ADDRESS
#          value: "0.0.0.0:8088"
        - name: INFLUXDB_HTTP_AUTH_ENABLED
          value: "true"
        - name: INFLUXDB_HTTP_LOG_ENABLED
          value: "true"
#        - name: INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED
#          value: "true"
#        - name: INFLUXDB_COORDINATOR_WRITE_TIMEOUT
#          value: "1s"
#        - name: INFLUXDB_HTTP_FLUX_ENABLED
#          value: "true"
#        - name: INFLUXDB_HTTP_BIND_ADDRESS
#          value: "0.0.0.0:8086"
#        - name: INFLUXDB_HTTP_WRITE_TRACING
#          value: "true"
        - name: INFLUXDB_LOGGING_LEVEL
          value: "debug"
#        - name: INFLUXDB_DATA_TRACE_LOGGING_ENABLED
#          value: "true"
      ports:
        - containerPort: 8086
          name: "http"
        - containerPort: 8088
          name: "udp"
      volumeMounts:
        - mountPath: /var/lib/influxdb
          name: edgex-influxdb-data
  volumes:
    - name: edgex-influxdb-data
      persistentVolumeClaim:
        claimName: edgex-influxdb-data-claim
